name: SetSpawn
version: '${project.version}'
main: me.pandauprising.setspawn.SetSpawn
api-version: 1.20
authors: [ PandaUprising ]
description: This plugin allows you to set a spawn point for your server and teleport back to it
commands:
  SetSpawn:
    description: Set the spawn point for your server
    usage: /<command>
    aliases:
      - ss
  spawn:
    description: Teleport you to the spawn point
    usage: /<command>
    aliases:
      - sp